use_frameworks!

platform :ios, '10.0'

target 'VVSequelize_Example' do
  pod 'VVSequelize', :path => '../'
  pod 'CocoaLumberjack'

  target 'VVSequelize_Tests' do
    inherit! :search_paths
  end
end
