#use_frameworks!
inhibit_all_warnings!

target 'VVSequelize_Example' do
  pod 'VVSequelize', :path => '../'

  target 'VVSequelize_Tests' do
    inherit! :search_paths
    pod 'MJExtension'
  end
end
